language: python

python:
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"

addons:
    apt:
        packages:
            - gcc
            - g++
            - make
            - autoconf
            - libtool
            - libpng-dev
            - libjpeg-dev
            - libgif-dev
            - libssl-dev
            - libyaml-dev
            - libsqlite3-dev
            - libpq-dev
            - libmysqlclient-dev

before_install:
    - pip install invoke nose
    - inv install_libotama

install:
    - python setup.py --quiet build --build-base=".build-$TRAVIS_PYTHON_VERSION" install

script:
    - nosetests -w test

after_success:
    # pypy is too slow.
    - if [ "$TRAVIS_PYTHON_VERSION" != "pypy" ]; then ./coveralls.bash; fi
