language: python

python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"

install:
    - pip install invoke
    - inv install_libotama
    - python setup.py --quiet build --build-base=".build-$TRAVIS_PYTHON_VERSION" install

script:
    - python test/test_otama.py

after_success:
    # pypy is too slow.
    - if [ "$TRAVIS_PYTHON_VERSION" != "pypy" ]; then ./coveralls.bash; fi
